#!/usr/bin/env python3
"""Regenerate coverage.md: every inventory defect -> spec -> fix step(s) -> wave.

Run from docs/plugin-rewrite/:  python3 phase3/gen_coverage.py evidence/defect-index.txt coverage.md
Reads specs/S*.md section 1.3 tables and the defined step ids of section 3.
Prints a check summary to stderr; exit 1 if any defect is unmapped, mapped twice,
or cites a step id that no spec defines.
"""
import collections
import glob
import re
import sys

STEP = re.compile(r"S\d{2}-W\d[a-z]?-[0-9]+[a-z]?")


def defined_steps():
    out = {}
    for f in sorted(glob.glob("specs/S*.md")):
        t = open(f, encoding="utf-8").read()
        m = re.search(r"^## 3\. Change steps.*?(?=^## 4\. )", t, re.S | re.M)
        for line in (m.group(0) if m else "").splitlines():
            mm = re.match(r"^(?:\*\*|#{3,4} |\| ?\*?\*?|- \*\*)(S\d{2}-W\d[a-z]?-[0-9A-Za-z]+)", line)
            if mm:
                out.setdefault(mm.group(1), f)
    return out


def main(index_path, out_path):
    order, sev, text = [], {}, {}
    for line in open(index_path, encoding="utf-8"):
        m = re.match(r"^(.+?-\d+) \[(\w+)\] (.*)$", line.rstrip("\n"))
        if m:
            order.append(m.group(1))
            sev[m.group(1)] = m.group(2)
            text[m.group(1)] = m.group(3)
    ids = set(order)
    rows = collections.defaultdict(list)
    for f in sorted(glob.glob("specs/S*.md")):
        spec = re.match(r"specs/(S\d{2})", f).group(1)
        t = open(f, encoding="utf-8").read()
        m = re.search(r"^#{2,3} 1\.3 .*?(?=^#{2,3} 1\.4 |^## 2\. )", t, re.S | re.M)
        if not m:
            print(f"WARN no 1.3 section in {f}", file=sys.stderr)
            continue
        for line in m.group(0).splitlines():
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if not cells or cells[0].strip("*` ") not in ids:
                continue
            did = cells[0].strip("*` ")
            h = re.search(r"H\d{2}", " ".join(cells[1:3]))
            fix = " ".join(cells[-2:])
            steps = sorted(set(STEP.findall(fix))) or sorted(set(STEP.findall(" ".join(cells[1:]))))
            wm = re.search(r"W\d(?:\s*[,/–-]\s*W\d)*", cells[-1]) or re.search(r"\(W\d[^)]*\)", " ".join(cells[1:]))
            wave = wm.group(0).strip("()") if wm else ""
            deferred = bool(re.search(r"defer|ratchet", fix, re.I))
            rows[did].append((spec, h.group(0) if h else "", steps, wave, deferred))
    defs = defined_steps()
    unmapped = [d for d in order if d not in rows]
    multi = [d for d in order if len(rows.get(d, [])) > 1]
    dangling = sorted({s for rs in rows.values() for r in rs for s in r[2] if s not in defs})
    nostep = [d for d in order if d in rows and not any(r[2] for r in rows[d])]
    counts = collections.Counter(sev[d] for d in order)
    L = [
        "# Defect coverage (313 inventory defects → spec → fix step → wave)",
        "",
        "Generated by `phase3/gen_coverage.py` from the §1.3 tables of the specs and the step ids",
        "defined in their §3. `H` = HIGH defect number from architecture Appendix A. A row whose",
        "fix column names no step id is a deferral (ratchet entry) or a spec-level note; see the spec.",
        "",
        f"Totals: {len(order)} defects ({counts.get('high',0)} high, {counts.get('medium',0)} medium, "
        f"{counts.get('low',0)} low); {len(order)-len(unmapped)} mapped to a spec; "
        f"{len(order)-len(unmapped)-len(nostep)} with at least one step id; "
        f"{sum(1 for d in nostep if any(r[4] for r in rows[d]))} deferred to the ratchet; "
        f"{len(defs)} step ids defined across the specs.",
        "",
    ]
    prefix = None
    for d in order:
        p = re.sub(r"-\d+$", "", d)
        if p != prefix:
            prefix = p
            L += ["", f"## {p}", "", "| Id | Sev | H | Spec | Fix step(s) | Wave | Defect |", "|---|---|---|---|---|---|---|"]
        for spec, h, steps, wave, deferred in rows.get(d, [("—", "", [], "", False)]):
            st = ", ".join(steps) if steps else ("deferred (ratchet)" if deferred else "see spec")
            desc = text[d][:90].replace("|", "\\|")
            L.append(f"| {d} | {sev[d]} | {h} | {spec} | {st} | {wave} | {desc} |")
    open(out_path, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"defects {len(order)} unmapped {len(unmapped)} multi {len(multi)} "
          f"no-step {len(nostep)} dangling-step-ids {len(dangling)} defined-steps {len(defs)}", file=sys.stderr)
    for name, lst in (("UNMAPPED", unmapped), ("MULTI", multi), ("DANGLING", dangling), ("NOSTEP", nostep)):
        if lst:
            print(name, " ".join(lst), file=sys.stderr)
    return 1 if (unmapped or multi or dangling) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2]))
