#!/usr/bin/env python3
"""Regenerate ROUTING.md — the marketplace's request-to-plugin router.

Reads the catalog and every plugin's components (skills, commands, agents) and
writes a single lookup table at the repo root. The `/route` command and any
human browsing the repo read this file to pick the right skill/plugin for a
request. It is a GENERATED artifact: never hand-edit ROUTING.md — rerun this.

    python scripts/route.py     # fall back to: python3 scripts/route.py

Kept in sync automatically: /new-plugin and /refine-plugin run this after they
register or edit a plugin, so a new or changed skill shows up in the router
without a manual step.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MKT = os.path.join(ROOT, ".claude-plugin", "marketplace.json")
OUT = os.path.join(ROOT, "ROUTING.md")


def frontmatter(path):
    """Parse YAML frontmatter (name + description) without pyyaml.

    Same folding rules as scripts/validate.py: a folded block scalar (`>-`) and
    indented continuation lines collapse into one string.
    """
    text = open(path, encoding="utf-8").read()
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return {}
    fields, key = {}, None
    for line in match.group(1).split("\n"):
        header = re.match(r"^(\w[\w-]*):\s*(.*)$", line)
        if header:
            key = header.group(1)
            value = header.group(2).strip()
            fields[key] = "" if value in (">-", ">", "|", "|-") else value
        elif key and line.startswith("  "):
            fields[key] = (fields[key] + " " + line.strip()).strip()
    return fields


def first_sentence(text, cap=160):
    """A short trigger cue for the quick index: the description's first sentence."""
    text = " ".join(text.split())
    cue = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0] if text else ""
    return (cue[: cap - 1].rstrip() + "…") if len(cue) > cap else cue


def components(pdir):
    """Collect (kind, name, invoke, description) for one plugin, in a stable order."""
    items = []

    skills_dir = os.path.join(pdir, "skills")
    if os.path.isdir(skills_dir):
        for skill in sorted(os.listdir(skills_dir)):
            sp = os.path.join(skills_dir, skill, "SKILL.md")
            if os.path.isfile(sp):
                fm = frontmatter(sp)
                items.append(("skill", fm.get("name", skill),
                              f"skill `{fm.get('name', skill)}`", fm.get("description", "")))

    cmd_dir = os.path.join(pdir, "commands")
    if os.path.isdir(cmd_dir):
        for cmd in sorted(f for f in os.listdir(cmd_dir) if f.endswith(".md")):
            fm = frontmatter(os.path.join(cmd_dir, cmd))
            base = cmd[:-3]
            items.append(("command", base, f"`/{base}`", fm.get("description", "")))

    agent_dir = os.path.join(pdir, "agents")
    if os.path.isdir(agent_dir):
        for agent in sorted(f for f in os.listdir(agent_dir) if f.endswith(".md")):
            fm = frontmatter(os.path.join(agent_dir, agent))
            name = fm.get("name", agent[:-3])
            items.append(("agent", name, f"agent `{name}`", fm.get("description", "")))

    return items


def cell(text):
    """Escape a value for a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def main():
    mkt = json.load(open(MKT, encoding="utf-8"))
    plugins = mkt["plugins"]

    catalog = {p["name"]: components(os.path.join(ROOT, p["source"])) for p in plugins}

    lines = [
        f"# ROUTING — {mkt['name']}",
        "",
        "_Auto-generated by `scripts/route.py`. Do not edit by hand — rerun the script "
        "(it runs automatically after `/new-plugin` and `/refine-plugin`)._",
        "",
        "Match the request to the row whose **Use when** fits, then take its **Route**. "
        "Skills fire automatically from their own descriptions; commands are invoked with "
        "a slash. This table is a fast index over the same descriptions Claude already routes on.",
        "",
        "## Quick index",
        "",
        "| Use when the request is about… | Plugin | Route |",
        "| --- | --- | --- |",
    ]

    for p in plugins:
        for kind, name, invoke, desc in catalog[p["name"]]:
            cue = first_sentence(desc) or cell(p["description"])
            lines.append(f"| {cell(cue)} | {p['name']} | {invoke} |")

    lines += ["", "## Plugins", ""]

    for p in plugins:
        cat = p.get("category", "")
        header = f"### {p['name']}" + (f" — {cat}" if cat else "") + f"  _v{p['version']}_"
        lines.append(header)
        lines.append("")
        lines.append(cell(p["description"]))
        if p.get("keywords"):
            lines.append("")
            lines.append("Keywords: " + ", ".join(p["keywords"]))
        lines.append("")
        for kind, name, invoke, desc in catalog[p["name"]]:
            lines.append(f"- **{invoke}** ({kind}) — {cell(first_sentence(desc, cap=220)) or '—'}")
        lines.append("")

    open(OUT, "w", encoding="utf-8").write("\n".join(lines).rstrip() + "\n")
    total = sum(len(v) for v in catalog.values())
    print(f"ROUTING.md regenerated: {len(plugins)} plugins, {total} components.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
